#!/usr/bin/env bash
# init-scripts — 一次備妥消費端的 scripts/：產生轉發 shim，並複製 sample/ 內
# link-scripts 產不出來的消費端自有腳本。新開 monorepo 時執行一次即可。
#
# 用法:
#   ./monorepo-scripts/init-scripts.sh
#
# 嚴禁改成複製 sample/ 內的 shim。那些 shim 把「從 scripts/ 走到工具集」的相對路徑
# 寫死成 ../monorepo-scripts/，只在工具集掛於 root 下一層時正確；掛在
# tools/monorepo-scripts 時必須由 link-scripts 依實際掛載位置重算。因此 shim 一律
# 交給 link-scripts 產生，本腳本只補它涵蓋不到的檔案。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/repo-context.sh"
ROOT_DIR="$(resolve_repo_root "$SCRIPT_DIR")"

SAMPLE_DIR="$SCRIPT_DIR/sample"
SCRIPTS_DIR="$ROOT_DIR/scripts"
MARKER="AUTO-GENERATED by monorepo-scripts/link-scripts"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if [ ! -d "$SAMPLE_DIR" ]; then
    echo -e "${RED}ERROR: 找不到 sample/：$SAMPLE_DIR${NC}" >&2
    exit 1
fi

# --- 挑出「link-scripts 產不出來」的檔案 ---
# 判準是檔案內容有無 AUTO-GENERATED marker，不是寫死的檔名清單：sample/ 日後增減
# 自有腳本時本腳本不必跟著改，誤放進 sample/ 的 shim 也會自動被排除。
declare -a OWN=()
for f in "$SAMPLE_DIR"/*; do
    [ -f "$f" ] || continue
    base="$(basename "$f")"
    # 用白名單而非黑名單：只有腳本會進消費端 scripts/。擋 .md 的黑名單會讓兩版行為分歧
    # ——bash 的 *.md 分大小寫、PowerShell 的 -eq '.md' 不分，SAMPLE.MD 只會被其中一版擋下。
    case "$base" in *.sh|*.ps1) ;; *) continue ;; esac
    # marker 只認檔頭：shim 的 marker 固定在第 1~2 行。限定範圍才不會在自有腳本的註解或
    # 字串剛好提到這段文字時，把它誤判成 shim 而漏複製。
    # 用 case 而非管線接 grep：grep -q 命中後會提前結束，pipefail 下 head 的 SIGPIPE(141)
    # 會蓋掉 grep 的 0，使判斷反轉。case 的比對分大小寫，與 .ps1 版的 String.Contains 一致。
    head_txt="$(head -n 2 "$f")"
    case "$head_txt" in *"$MARKER"*) continue ;; esac
    OWN+=("$base")
done

if [ "${#OWN[@]}" -eq 0 ]; then
    echo -e "${RED}ERROR: sample/ 內沒有任何非 shim 的自有腳本可複製${NC}" >&2
    exit 1
fi

# --- preflight：先驗後寫 ---
# 自有腳本不帶 marker，link-scripts 的 collision 防護涵蓋不到它們；直接覆蓋會無聲
# 蓋掉消費端已修改的版本，因此任一目標已存在就整批中止，交由人工處理。
declare -a EXISTING=()
for base in "${OWN[@]}"; do
    if [ -e "$SCRIPTS_DIR/$base" ] || [ -L "$SCRIPTS_DIR/$base" ]; then
        EXISTING+=("scripts/$base")
    fi
done
if [ "${#EXISTING[@]}" -gt 0 ]; then
    echo -e "${RED}ERROR: 下列檔案已存在，拒絕覆蓋：${NC}" >&2
    printf '       %s\n' "${EXISTING[@]}" >&2
    echo "       確認不需保留後自行刪除，再重跑本腳本。" >&2
    echo "       若上次執行中途失敗，scripts/ 可能只有部分檔案，請一併檢視。" >&2
    exit 1
fi

# --- 先產生 shim ---
# link-scripts 有自己的 collision preflight。被它擋下時本腳本尚未寫入任何檔案，
# 消費端 scripts/ 維持原狀。
echo -e "${CYAN}=== 產生轉發 shim ===${NC}"
if ! bash "$SCRIPT_DIR/link-scripts.sh"; then
    echo -e "${RED}ERROR: link-scripts 失敗，未複製任何自有腳本${NC}" >&2
    exit 1
fi

# --- 再複製自有腳本 ---
# 一律用 cp 做位元組複製：normalize-git-eol.ps1 帶 UTF-8 BOM，經任何文字讀寫
# 迴圈都可能被剝除，而 Windows PowerShell 5.1 少了 BOM 會解析錯中文內容。
echo
echo -e "${CYAN}=== 複製消費端自有腳本 ===${NC}"
for base in "${OWN[@]}"; do
    cp -- "$SAMPLE_DIR/$base" "$SCRIPTS_DIR/$base"
    case "$base" in
        *.sh)
            chmod +x "$SCRIPTS_DIR/$base" 2>/dev/null || true
            git -C "$ROOT_DIR" update-index --add --chmod=+x "scripts/$base"
            ;;
    esac
    echo "copied: scripts/$base"
done

echo
echo -e "${GREEN}[OK] scripts/ 已備妥：$SCRIPTS_DIR${NC}"
