# init-scripts — 一次備妥消費端的 scripts/：產生轉發 shim，並複製 sample/ 內
# link-scripts 產不出來的消費端自有腳本。新開 monorepo 時執行一次即可。
#
# 用法:
#   ./monorepo-scripts/init-scripts.ps1
#
# 嚴禁改成複製 sample/ 內的 shim。那些 shim 把「從 scripts/ 走到工具集」的相對路徑
# 寫死成 ..\monorepo-scripts\，只在工具集掛於 root 下一層時正確；掛在
# tools\monorepo-scripts 時必須由 link-scripts 依實際掛載位置重算。因此 shim 一律
# 交給 link-scripts 產生，本腳本只補它涵蓋不到的檔案。
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding          = [System.Text.Encoding]::UTF8

. (Join-Path $PSScriptRoot "lib/repo-context.ps1")

$scriptDir  = $PSScriptRoot
$rootDir    = Get-ConsumerRepoRoot -ScriptDir $scriptDir
$sampleDir  = Join-Path $scriptDir "sample"
$scriptsDir = Join-Path $rootDir "scripts"
$marker     = "AUTO-GENERATED by monorepo-scripts/link-scripts"

if (-not (Test-Path $sampleDir -PathType Container)) {
    Write-Error "找不到 sample/:$sampleDir"; exit 1
}

# --- 挑出「link-scripts 產不出來」的檔案 ---
# 判準是檔案內容有無 AUTO-GENERATED marker,不是寫死的檔名清單:sample/ 日後增減
# 自有腳本時本腳本不必跟著改,誤放進 sample/ 的 shim 也會自動被排除。
$own = @()
foreach ($f in (Get-ChildItem -Path $sampleDir -File)) {
    # 用白名單而非黑名單:只有腳本會進消費端 scripts/。擋 .md 的黑名單會讓兩版行為分歧
    # ——PowerShell 的 -eq 不分大小寫、bash 的 *.md 分大小寫,SAMPLE.MD 只會被其中一版擋下。
    # -cnotin 是分大小寫版本,與 .sh 版的 case 比對一致。
    if ($f.Extension -cnotin @('.sh','.ps1')) { continue }
    # marker 只認檔頭:shim 的 marker 固定在第 1~2 行。限定範圍才不會在自有腳本的註解或
    # 字串剛好提到這段文字時,把它誤判成 shim 而漏複製。
    # 讀取必須指定 -Encoding UTF8:自有腳本含中文,5.1 預設以 OEM (CP950) 解碼會吃掉換行。
    # 比對用 String.Contains(ordinal、分大小寫),不可用 -match:後者預設不分大小寫,與 .sh 版分歧。
    $isShim = $false
    foreach ($line in (Get-Content -LiteralPath $f.FullName -TotalCount 2 -Encoding UTF8)) {
        if ($line -and $line.Contains($marker)) { $isShim = $true }
    }
    if ($isShim) { continue }
    $own += $f.Name
}

if ($own.Count -eq 0) {
    Write-Error "sample/ 內沒有任何非 shim 的自有腳本可複製"; exit 1
}

# --- preflight:先驗後寫 ---
# 自有腳本不帶 marker,link-scripts 的 collision 防護涵蓋不到它們;直接覆蓋會無聲
# 蓋掉消費端已修改的版本,因此任一目標已存在就整批中止,交由人工處理。
$existing = @()
foreach ($base in $own) {
    $target = Join-Path $scriptsDir $base
    if (Get-Item -LiteralPath $target -Force -ErrorAction SilentlyContinue) {
        $existing += "scripts/$base"
    }
}
if ($existing.Count -gt 0) {
    Write-Host "[X] ERROR: 下列檔案已存在,拒絕覆蓋:" -ForegroundColor Red
    foreach ($e in $existing) { Write-Host "       $e" -ForegroundColor Red }
    Write-Host "       確認不需保留後自行刪除,再重跑本腳本。" -ForegroundColor Yellow
    Write-Host "       若上次執行中途失敗,scripts/ 可能只有部分檔案,請一併檢視。" -ForegroundColor Yellow
    exit 1
}

# --- 先產生 shim ---
# link-scripts 有自己的 collision preflight。被它擋下時本腳本尚未寫入任何檔案,
# 消費端 scripts/ 維持原狀。
Write-Host "=== 產生轉發 shim ===" -ForegroundColor Cyan
# link-scripts.ps1 的每個失敗路徑都是 Write-Error + exit,而它自身第一行就設
# $ErrorActionPreference = 'Stop',因此 Write-Error 會拋出並被下面的 catch 攔截(已實測)。
# 額外檢查 $LASTEXITCODE 是防守用:日後若出現不經 Write-Error 的裸 exit,才不會被無聲略過。
$global:LASTEXITCODE = 0
try {
    & (Join-Path $scriptDir "link-scripts.ps1")
} catch {
    Write-Host "[X] ERROR: link-scripts 失敗,未複製任何自有腳本" -ForegroundColor Red
    throw
}
if ($LASTEXITCODE -ne 0) {
    Write-Host "[X] ERROR: link-scripts 失敗 (exit $LASTEXITCODE),未複製任何自有腳本" -ForegroundColor Red
    exit 1
}

# --- 再複製自有腳本 ---
# 一律用 Copy-Item 做位元組複製:normalize-git-eol.ps1 帶 UTF-8 BOM,經任何文字
# 讀寫迴圈都可能被剝除,而 Windows PowerShell 5.1 少了 BOM 會解析錯中文內容。
Write-Host ""
Write-Host "=== 複製消費端自有腳本 ===" -ForegroundColor Cyan
foreach ($base in $own) {
    Copy-Item -LiteralPath (Join-Path $sampleDir $base) -Destination (Join-Path $scriptsDir $base)
    if ($base -like '*.sh') {
        & git -C $rootDir update-index --add --chmod=+x "scripts/$base"
        if ($LASTEXITCODE -ne 0) { Write-Error "git update-index 失敗 (exit $LASTEXITCODE):scripts/$base"; exit 1 }
    }
    Write-Host "copied: scripts/$base"
}

Write-Host ""
Write-Host "[OK] scripts/ 已備妥:$scriptsDir" -ForegroundColor Green
