$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot "lib/repo-context.ps1")

$scriptDir  = $PSScriptRoot
$rootDir    = Get-ConsumerRepoRoot -ScriptDir $scriptDir

# shim 內嵌「從 scripts/ 走到本工具集」的相對路徑,而非固定的一層目錄名,
# 這樣掛在 tools/monorepo-scripts 這種較深的位置也能正確轉發。
$monoRel = Get-PathRelativeToRoot -Root $rootDir -Path $scriptDir
if (-not $monoRel) {
    Write-Error "本工具集不在解析到的 repo root 之下,無法產生 shim (root:$rootDir 工具集:$scriptDir)"; exit 1
}
foreach ($seg in ($monoRel -split '[\\/]')) {
    if ($seg -notmatch '^[A-Za-z0-9._-]+$') { Write-Error "產生器路徑含不安全字元,無法安全嵌入 shim:$monoRel"; exit 1 }
}
$monoRelWin = $monoRel -replace '/', '\'
$monoRelSh  = $monoRel -replace '\\', '/'

$scriptsDir = Join-Path $rootDir "scripts"
$marker     = "AUTO-GENERATED by monorepo-scripts/link-scripts"

if (-not (Test-Path $scriptsDir -PathType Container)) {
    New-Item -ItemType Directory -Path $scriptsDir | Out-Null
    Write-Host "created: scripts/ (consumer 尚無此目錄)"
}

function Test-Managed([string]$path) {
    return (Test-Path $path -PathType Leaf) -and ((Get-Content -Raw -LiteralPath $path) -match [regex]::Escape($marker))
}

# 只有「不存在」或「本工具產生的一般檔案」才允許覆寫。目錄、symlink/junction、
# 以及目標已消失的 dangling symlink 一律視為 collision:沿 symlink 寫入會把檔案
# 寫到 scripts/ 之外。與 link-scripts.sh 的 -L 防護行為一致。
function Test-Overwritable([string]$path) {
    $item = Get-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
    if (-not $item) { return $true }
    if ($item.PSIsContainer) { return $false }
    if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) { return $false }
    return (Test-Managed $path)
}

# --- 探索 ---
$stems = @()
Get-ChildItem -Path $scriptDir -Filter *.sh -File | ForEach-Object {
    $stem = $_.BaseName
    if ($stem -eq 'link-scripts') { return }
    if ($stem -notmatch '^[A-Za-z0-9._-]+$') { Write-Error "不合法的 stem:$stem"; exit 1 }
    if (-not (Test-Path (Join-Path $scriptDir "$stem.ps1"))) { Write-Error "$stem 缺少對應的 .ps1,不成對"; exit 1 }
    $stems += $stem
}
if ($stems.Count -eq 0) { Write-Error "未找到任何可連結的公開入口"; exit 1 }

# --- 反向檢查:孤兒 .ps1 也要 fail-fast ---
Get-ChildItem -Path $scriptDir -Filter *.ps1 -File | ForEach-Object {
    $pstem = $_.BaseName
    if ($pstem -eq 'link-scripts') { return }
    if (-not (Test-Path (Join-Path $scriptDir "$pstem.sh"))) { Write-Error "$pstem 有 .ps1 但缺對應的 .sh,不成對"; exit 1 }
}

# --- collision preflight(先驗後寫) ---
foreach ($stem in $stems) {
    foreach ($ext in @('sh','ps1')) {
        $target = Join-Path $scriptsDir "$stem.$ext"
        if (-not (Test-Overwritable $target)) {
            Write-Error "scripts/$stem.$ext 已存在且非本工具產生的一般檔案,拒絕覆蓋(collision)"; exit 1
        }
    }
}

$enc = New-Object System.Text.UTF8Encoding($false)

foreach ($stem in $stems) {
    $sh = "#!/usr/bin/env bash`n" +
          "# $marker; do not edit, re-run the generator.`n" +
          "exec bash `"`$(dirname `"`${BASH_SOURCE[0]}`")/../$monoRelSh/$stem.sh`" `"`$@`"`n"
    [System.IO.File]::WriteAllText((Join-Path $scriptsDir "$stem.sh"), $sh, $enc)

    $ps = "# $marker; do not edit, re-run the generator.`n" +
          "`$t = Join-Path `$PSScriptRoot `"..\$monoRelWin\$stem.ps1`"`n" +
          "if (-not (Test-Path `$t)) { Write-Error `"linked target missing: `$t`"; exit 1 }`n" +
          "& `$t @args`n" +
          "exit `$LASTEXITCODE`n"
    [System.IO.File]::WriteAllText((Join-Path $scriptsDir "$stem.ps1"), $ps, $enc)

    try { & git -C $rootDir update-index --add --chmod=+x "scripts/$stem.sh" 2>$null } catch {}
    if ($LASTEXITCODE -ne 0) { Write-Error "git update-index 失敗 (exit $LASTEXITCODE):scripts/$stem.sh"; exit 1 }
    Write-Host "linked: scripts/$stem.sh, scripts/$stem.ps1"
}

# --- stale 報告(只報不刪) ---
Get-ChildItem -Path $scriptsDir -File | Where-Object { $_.Extension -in '.sh','.ps1' } | ForEach-Object {
    if (-not (Test-Managed $_.FullName)) { return }
    $stem = $_.BaseName
    if ((-not (Test-Path (Join-Path $scriptDir "$stem.sh"))) -or (-not (Test-Path (Join-Path $scriptDir "$stem.ps1")))) {
        Write-Warning "STALE: scripts/$($_.Name) 的來源已不存在,請人工檢視"
    }
}
