#!/usr/bin/env bash
# link-scripts — 在 consumer repo 的 scripts/ 生成轉發 shim,讓通用工具能從 scripts/ 操作,
# 實作仍留在獨立的 monorepo-scripts submodule。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/repo-context.sh"
ROOT_DIR="$(resolve_repo_root "$SCRIPT_DIR")"

# shim 內嵌「從 scripts/ 走到本工具集」的相對路徑,而非固定的一層目錄名,
# 這樣掛在 tools/monorepo-scripts 這種較深的位置也能正確轉發。
MONO_REL="$(path_relative_to_root "$ROOT_DIR" "$SCRIPT_DIR")" || MONO_REL=""
if [ -z "$MONO_REL" ]; then
    echo "ERROR: 本工具集不在解析到的 repo root 之下,無法產生 shim" >&2
    echo "       repo root:$ROOT_DIR" >&2
    echo "       工具集位置:$SCRIPT_DIR" >&2
    exit 1
fi
IFS='/' read -ra MONO_SEGS <<< "$MONO_REL"
for seg in "${MONO_SEGS[@]}"; do
    if ! [[ "$seg" =~ ^[A-Za-z0-9._-]+$ ]]; then
        echo "ERROR: 產生器路徑含不安全字元,無法安全嵌入 shim:$MONO_REL" >&2
        exit 1
    fi
done
MONO_REL_WIN="${MONO_REL//\//\\}"

SCRIPTS_DIR="$ROOT_DIR/scripts"
MARKER="AUTO-GENERATED by monorepo-scripts/link-scripts"

if [ ! -d "$SCRIPTS_DIR" ]; then
    mkdir -p "$SCRIPTS_DIR"
    echo "created: scripts/ (consumer 尚無此目錄)"
fi

is_managed() { [ -f "$1" ] && grep -q "$MARKER" "$1"; }

# --- 探索公開入口:頂層成對 .sh+.ps1、stem 合法、排除自己 ---
declare -a STEMS=()
for sh in "$SCRIPT_DIR"/*.sh; do
    [ -e "$sh" ] || continue
    stem="$(basename "$sh" .sh)"
    [ "$stem" = "link-scripts" ] && continue
    if ! [[ "$stem" =~ ^[A-Za-z0-9._-]+$ ]]; then
        echo "ERROR: 不合法的 stem:$stem" >&2
        exit 1
    fi
    if [ ! -f "$SCRIPT_DIR/$stem.ps1" ]; then
        echo "ERROR: $stem 缺少對應的 .ps1,不成對" >&2
        exit 1
    fi
    STEMS+=("$stem")
done
if [ "${#STEMS[@]}" -eq 0 ]; then
    echo "ERROR: 未找到任何可連結的公開入口" >&2
    exit 1
fi

# 反向檢查:孤兒 .ps1(有 .ps1 無對應 .sh)也要 fail-fast,確保雙向成對
for ps in "$SCRIPT_DIR"/*.ps1; do
    [ -e "$ps" ] || continue
    pstem="$(basename "$ps" .ps1)"
    [ "$pstem" = "link-scripts" ] && continue
    if [ ! -f "$SCRIPT_DIR/$pstem.sh" ]; then
        echo "ERROR: $pstem 有 .ps1 但缺對應的 .sh,不成對" >&2
        exit 1
    fi
done

# --- collision preflight:scripts/ 若已有同名檔且非 managed,整批中止(先驗後寫) ---
for stem in "${STEMS[@]}"; do
    for ext in sh ps1; do
        target="$SCRIPTS_DIR/$stem.$ext"
        # 有任何檔案系統物件(含目錄、symlink、dangling symlink)但不是本工具產生的一般檔就中止,
        # 避免寫到一半才失敗,或被 symlink 導向寫到 scripts/ 外。
        if [ -e "$target" ] || [ -L "$target" ]; then
            if [ -L "$target" ] || [ ! -f "$target" ] || ! is_managed "$target"; then
                echo "ERROR: scripts/$stem.$ext 已存在且非本工具產生的一般檔案,拒絕覆蓋(collision)" >&2
                exit 1
            fi
        fi
    done
done

# --- 寫入成對 shim ---
for stem in "${STEMS[@]}"; do
    printf '%s\n' \
        '#!/usr/bin/env bash' \
        "# $MARKER; do not edit, re-run the generator." \
        "exec bash \"\$(dirname \"\${BASH_SOURCE[0]}\")/../$MONO_REL/$stem.sh\" \"\$@\"" \
        > "$SCRIPTS_DIR/$stem.sh"

    printf '%s\n' \
        "# $MARKER; do not edit, re-run the generator." \
        "\$t = Join-Path \$PSScriptRoot \"..\\$MONO_REL_WIN\\$stem.ps1\"" \
        "if (-not (Test-Path \$t)) { Write-Error \"linked target missing: \$t\"; exit 1 }" \
        "& \$t @args" \
        'exit $LASTEXITCODE' \
        > "$SCRIPTS_DIR/$stem.ps1"

    git -C "$ROOT_DIR" update-index --add --chmod=+x "scripts/$stem.sh"
    chmod +x "$SCRIPTS_DIR/$stem.sh" 2>/dev/null || true
    echo "linked: scripts/$stem.sh, scripts/$stem.ps1"
done

# --- stale 報告(只報不刪):帶 marker 但來源 .sh/.ps1 有任一不存在 ---
for f in "$SCRIPTS_DIR"/*.sh "$SCRIPTS_DIR"/*.ps1; do
    [ -e "$f" ] || continue
    is_managed "$f" || continue
    base="$(basename "$f")"; stem="${base%.*}"
    if [ ! -f "$SCRIPT_DIR/$stem.sh" ] || [ ! -f "$SCRIPT_DIR/$stem.ps1" ]; then
        echo "STALE: scripts/$base 的來源已不存在,請人工檢視(git diff / rm)" >&2
    fi
done
