# AUTO-GENERATED by monorepo-scripts/link-scripts; do not edit, re-run the generator.
$t = Join-Path $PSScriptRoot "..\monorepo-scripts\sync-remote-branches.ps1"
if (-not (Test-Path $t)) { Write-Error "linked target missing: $t"; exit 1 }
& $t @args
exit $LASTEXITCODE
